s = ""
print("File read using 'read()'")
f = open("classwork56.txt")
s = f.read()
print(s)
f.close()
print("-"*41)
print("File read using 'readline()'")
f = open("classwork56.txt")
print(f.readline())
print(f.readline())
print(f.readline())
print(f.readline())
f.close()
print("-"*41)
print("File read using loop")
f = open("classwork56.txt")
for i in f:
    print(i)
f.close()
print("-"*41)
print("Performing read, append, write in the specified order")
f = open("classwork56.txt", "r")
print("File opened in read 'r' mode")
print(f.read())
f.close()
print("-"*41)
f = open("classwork56.txt", "a")
print("Appending to file using append 'a' mode")
f.write("\nHehe :)")
f.close()
f = open("classwork56.txt")
print(f.read())
f.close()
print("-"*41)
f = open("classwork56.txt", "w")
print("Writing to file using write 'w' mode")
f.write("I am replacing the content, sorry :(")
f.close()
f = open("classwork56.txt")
print(f.read())
f.close()
print("-"*41)
# Just resetting the content of the file
f = open("classwork56.txt", "w")
f.write(s)
f.close()

# Creating new file
print("Now going to create a new file 'classwork56_new.txt'")
f = open("classwork56_new.txt", "a")
f.close()
print("Done")